language: java
jdk:
- oraclejdk8
notifications:
  email:
    recipients:
    - martin.oconnor@stanford.edu
    on_success: never
    on_failure: always
env:
  global:
  - secure: b5bShYYTcvJwLDKtsKn2qsjNeiNoO+sTUg5GWoWRnzOY3j4PFA7eK8R3gSN6detRcX91SwltYZ+BoCZhQ6scXeJdbwAx/Oc0NlpsxGc5YlZM+yGfOoksV3cY7aAPLATJa3E4WCnvulQ+tbI/+qIgxXefaJXUf2HC6LGOYFrz0w4=
  - secure: B8nverIiqzeXh4u8URkap/idtAKlrw286mRNHVUPiOuH8nCDbwyG88MTRxyGtC6H+x+Ix/VMggBazb9rolFVtNxokEHKWN4DaZ6DFDgcwmY0Xlt5gAXplWA2EdyAsu5O/TTuvJIQ5MqiaMFvNumVOjxmbDzbngvR+2uOQZvnFuE=
